services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # Cổng mà ứng dụng Go sẽ chạy
    environment:
      - MONGODB_URI=mongodb://root:rootpassword@mongo:27017
      - DATABASE_NAME=auth_db
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    # ports:
    #   - "27017:27017" # Cổng MongoDB
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword
    volumes:
      - mongo_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
volumes:
  mongo_data: